### ISSUE TITLE
在ios系统下也能嗅探视频直链了

### ISSUE THREAD

**Issue by dreampjk** [helson-lin/ffandown-violentmonkey-script#1]
iOS里的focus浏览器可以嗅探视频了
复制视频链接成功
下载弹窗不出来
在ios里试了几个浏览器  就这个focus支持脚本最强  要在里面选ALLFrame执行范围

**Comment by helson-lin** [comment]
> iOS里的focus浏览器可以嗅探视频了 复制视频链接成功 下载弹窗不出来 在ios里试了几个浏览器 就这个focus支持脚本最强 要在里面选ALLFrame执行范围

好的 感谢反馈，我后续增加到文档当中，手机端样式可能不适配需要调整一下
