### ISSUE TITLE
希望能在菜单里加一个“复制链接”的选项

### ISSUE THREAD

**Issue by 921j** [helson-lin/ffandown-violentmonkey-script#3]
![2024-09-25_231135](https://github.com/user-attachments/assets/f4bc5750-4b6f-436a-af38-aca68d7a9150)

如图，因为我用的是第三方的下载器，每次下载时，都要点一下猫咪图标→点一下“查看资源”→点一下弹窗里的URL复制→然后点一下网页其他地方关闭弹窗，步骤有点复杂。
所以希望能在图标的菜单里加一个“复制链接”的选项，或者支持中键点击图标复制链接的快捷键也行。
如果可以的话，再加一个可以获取资源的标题也可以免去手动复制的过程就更好了。
我用的“M3U8批量下载器”也挺好用的，支持加密 M3U8 的下载合并，用了很久了。

![2024-09-25_232321](https://github.com/user-attachments/assets/a944a030-d62d-4dff-9fc6-aeb7540c8f92)

谢谢！

**Comment by helson-lin** [comment]
一个页面可能解析到需要链接地址，这个复制按钮，直接复制所有的地址吗

**Comment by 921j** [comment]
可以默认复制清晰度最高和长度最长的那个吗？这样应该能排除广告干扰。
如果真的遇到有多个视频都是在同一页面且都需要的，再使用“查看资源”选择也行。或者做个序列，比如“复制资源A”、“复制资源B”；或者在“复制成功”的提示语后面加一句提醒也行，比如类似“检测到多个资源，已复制第一个（最长的、最清晰的）“之类的。

其实“M3U8批量下载器”也支持批量导入，不过我基本没用，我也很少遇到同一页面要下载多个M3U8的。
下面是这个软件的详细说明页，看起来功能很完整……
[https://www.yuque.com/yuqueyonghu5silcm/nrsc9k/dbgpn2](url)
推送也支持，但我在你的脚本中设置了没成功，应该是发送的参数不一样，要是我会改脚本就好了……

不好意思，我的请求似乎有点多，麻烦你了~

**Comment by helson-lin** [comment]
我整理一下看如何优化，最好的方式就是，给你一个快捷键，直接可以快速开关““查看资源””




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月27日 02:05 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/ffandown-violentmonkey-script] 希望能在菜单里加一个“复制链接”的选项 (Issue #3) |

可以默认复制清晰度最高和长度最长的那个吗？这样应该能排除有广告也是M3U8的情况了吧。。
如果真的遇到有多个视频都是在同一页面且都需要的，再使用“查看资源”选择也行，或者做个序列，比如“复制资源A”、“复制资源B”，或者在“复制成功”的提示语后面加一句提醒也行，比如类似“检测到多个资源，已默认复制（第一个、最长的、清晰度最高的）之类”
其实“M3U8批量下载器”也支持批量导入，不过我基本没用，也很少遇到同一页面要下载多个M3U8的，
不好意思，我的请求似乎有点多，麻烦你了~

**Comment by 921j** [comment]
--! 感觉还是避免不了打开和关闭弹窗的过程啊，也简化不了多少流程，还不如点击图标呢，，
如果是直接复制资源地址的快捷键更好，比如 Ctrl+1 复制第一个，Ctrl+2 复制第二个，…… 当然有多个资源的话就用把猫咪的颜色从白色变成大橘作提醒。。
我个人觉得最好的方式是能够自定义发送的参数，这样就能兼容任何支持推送的软件了，哈哈，怎么觉得这个脚本比下载工具有前途多了，下载的软件已经有很多了，各有各的优点，但能够很好的简化资源的“嗅探”与“获取”的过程的工具很难找的说。

**Comment by helson-lin** [comment]
你那个软件支持 api 调用嘛 “自定义”的概念范围太广了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月27日 15:14 |
| 收件人 | helson-lin/ffandown-violentmonkey-script ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown-violentmonkey-script] 希望能在菜单里加一个“复制链接”的选项 (Issue #3) |

--! 感觉还是避免不了打开和关闭弹窗的过程啊
我感觉最好的方式是能够自定义发送的参数，这样就能兼容任何支持推送的软件了，哈哈

**Comment by 921j** [comment]
支持的，那个说明页面里的“调用方式”里有，还有各种例子，不过我一个都不懂，，对于编程方面，我只一点点照猫画虎的假把式，深奥一点点就麻了……

**Comment by helson-lin** [comment]
你把调用方式截图我看下

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月27日 15:36 |
| 收件人 | ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown-violentmonkey-script] 希望能在菜单里加一个“复制链接”的选项 (Issue #3) |

支持的，那个说明页面里的“调用方式”里有，还有各种例子，不过我一个都不懂，，对于编程方面，我只一点点照猫画虎的假把式，深奥一点点就麻了……

**Comment by 921j** [comment]
https://www.yuque.com/yuqueyonghu5silcm/nrsc9k/yhoyr5

![1](https://github.com/user-attachments/assets/f517f94c-bec4-48e3-8180-76fdcd0a91fe)

![2](https://github.com/user-attachments/assets/9bdb99a9-ea7a-47c6-aa3c-b2830412d98b)

![3](https://github.com/user-attachments/assets/448d3e6e-6be5-4d19-8e3b-3799dd9cdfa7)

![4](https://github.com/user-attachments/assets/06c9dfe5-9f30-421d-a316-847d3195aeab)

**Comment by helson-lin** [comment]
解析的网站地址给一下，好调试。
这个软件是只有 windows 版本嘛，可是开源的，最好也给一下


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月27日 15:44 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/ffandown-violentmonkey-script] 希望能在菜单里加一个“复制链接”的选项 (Issue #3) |

https://www.yuque.com/yuqueyonghu5silcm/nrsc9k/yhoyr5

1.png (view on web)

2.png (view on web)

3.png (view on web)

4.png (view on web)

**Comment by 921j** [comment]
好像没有源码，只有发布地址，还有个易语言SDK：
https://www.52pojie.cn/thread-1631141-1-1.html

说明书网址，里面介绍得很详细：
https://www.yuque.com/yuqueyonghu5silcm/nrsc9k/yhoyr5

这是VBA调用的例子：
https://www.52pojie.cn/thread-1256288-1-1.html

这是Python调用的例子：
https://www.52pojie.cn/thread-1935228-1-1.html

这是NodeJS调用的例子：
https://www.52pojie.cn/thread-1256246-1-1.html

对不同分片自定义不同key：
https://www.52pojie.cn/thread-1799821-1-1.html



最近常用来下载的网址，这个比较纯净：
https://shise.me

带有广告和加密的网址，我用 N_m3u8DL-CLI 和 Downloader-M3U8 下载都不成功，用这个一下就成功了：
https://ypwlw.com
https://www.kpkuang.org


目前这个软件最大的问题是不知道如何保存设置，又不知道如何联系作者（听说有群正在找），比如我不喜欢转码，每次设置了"封装格式"为“RAW”，下次打开又自动变成“MP4”了；但是可以在调用参数里指定。

**Comment by helson-lin** [comment]
[bundle.js.zip](https://github.com/user-attachments/files/17171811/bundle.js.zip)
将这个 zip的内的bundle.js内容复制到油猴替换内容就可以了

配置如下：
<img width="326" alt="image" src="https://github.com/user-attachments/assets/873920c6-943a-4c8d-8ec9-62260610ed51">

**Comment by helson-lin** [comment]
你的这个软件api不支持title的推送，下载的名称不清楚会怎么命名

**Comment by 921j** [comment]
感谢大佬
但是发现没法用
1.我看 ffandown 的 issues 里有帖子说单击图标就可以发送推送吗，好像没作用；
2.点开“查看资源”，弹窗太长了，也不能移动，看不到后面的 “send”。
![2024-09-28_125217](https://github.com/user-attachments/assets/9067b9cd-9337-46e4-821b-a00e82d68a36)

**Comment by helson-lin** [comment]
稍等 我给你调整一下

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月28日 12:53 |
| 收件人 | helson-lin/ffandown-violentmonkey-script ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown-violentmonkey-script] 希望能在菜单里加一个“复制链接”的选项 (Issue #3) |

感谢大佬
但是发现没法用
1.我看 ffandown 的 issues 里有帖子说单击图标就可以发送推送吗，好像没作用；
2.点开“查看资源”，弹窗太长了，也不能移动，看不到后面的 “send”。
2024-09-28_125217.png (view on web)

**Comment by helson-lin** [comment]
[bundle.js.zip](https://github.com/user-attachments/files/17172831/bundle.js.zip)

**Comment by 921j** [comment]
这个可以推送了
带有广告的也可以分段下载
设置里按这样填写可以提取名称

`{"type": 2, "data": "$name,$url"}`

感谢大佬！！！再也不用切来切去了！

**Comment by helson-lin** [comment]
参数都是自定义的 这样配置没有问题的👍

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月28日 13:24 |
| 收件人 | helson-lin/ffandown-violentmonkey-script ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown-violentmonkey-script] 希望能在菜单里加一个“复制链接”的选项 (Issue #3) |

这个可以推送了
带有广告的也可以分段下载
设置里按这样填写可以提取名称

{"type": 2, "data": "$name,$url"}

感谢大佬！！！再也不用切来切去了！
